// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Composable, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetDomainsData, GetDomainsDomainIdRecordsData, GetNicUpdateData, GetNicUpdateError, GetNicUpdateResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostDomainsData, PostDomainsDomainIdRecordsData, PutDomainsDomainIdData, PutDomainsDomainIdRecordsRecordIdData } from './types.gen';

export type Options<TComposable extends Composable = '$fetch', TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = Options2<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * DDNSv2 Update Endpoint
 *
 * Endpoint for updating domain IP addresses using the DDNSv2 protocol.
 */
export const getNicUpdate = <TComposable extends Composable = '$fetch', DefaultT extends GetNicUpdateResponse = GetNicUpdateResponse>(options: Options<TComposable, GetNicUpdateData, GetNicUpdateResponse, DefaultT>) => (options.client ?? client).get<TComposable, GetNicUpdateResponse | DefaultT, GetNicUpdateError, DefaultT>({ url: '/nic/update', ...options });

/**
 * User Login
 *
 * Authenticate a user with their username and password
 */
export const postAuthLogin = <TComposable extends Composable = '$fetch', DefaultT extends PostAuthLoginResponse = PostAuthLoginResponse>(options: Options<TComposable, PostAuthLoginData, PostAuthLoginResponse, DefaultT>) => (options.client ?? client).post<TComposable, PostAuthLoginResponse | DefaultT, PostAuthLoginError, DefaultT>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Domains
 *
 * Retrieve a list of all domains owned by the authenticated user.
 */
export const getDomains = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, GetDomainsData, unknown, DefaultT>) => (options.client ?? client).get<TComposable, unknown | DefaultT, unknown, DefaultT>({
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/domains',
    ...options
});

export const postDomains = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, PostDomainsData, unknown, DefaultT>) => (options.client ?? client).post<TComposable, unknown | DefaultT, unknown, DefaultT>({
    url: '/domains',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const putDomainsDomainId = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, PutDomainsDomainIdData, unknown, DefaultT>) => (options.client ?? client).put<TComposable, unknown | DefaultT, unknown, DefaultT>({
    url: '/domains/{domainID}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getDomainsDomainIdRecords = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, GetDomainsDomainIdRecordsData, unknown, DefaultT>) => (options.client ?? client).get<TComposable, unknown | DefaultT, unknown, DefaultT>({ url: '/domains/{domainID}/records', ...options });

export const postDomainsDomainIdRecords = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, PostDomainsDomainIdRecordsData, unknown, DefaultT>) => (options.client ?? client).post<TComposable, unknown | DefaultT, unknown, DefaultT>({
    url: '/domains/{domainID}/records',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const putDomainsDomainIdRecordsRecordId = <TComposable extends Composable = '$fetch', DefaultT = undefined>(options: Options<TComposable, PutDomainsDomainIdRecordsRecordIdData, unknown, DefaultT>) => (options.client ?? client).put<TComposable, unknown | DefaultT, unknown, DefaultT>({
    url: '/domains/{domainID}/records/{recordID}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
