// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3003' | 'https://api.nowip.is-on.net' | (string & {});
};

export type GetNicUpdateData = {
    body?: never;
    path?: never;
    query: {
        hostname: string;
        myip: string | string;
    };
    url: '/nic/update';
};

export type GetNicUpdateErrors = {
    /**
     * Bad request due to missing or invalid parameters
     */
    400: string;
    /**
     * Authentication information is missing or invalid
     */
    401: string;
};

export type GetNicUpdateError = GetNicUpdateErrors[keyof GetNicUpdateErrors];

export type GetNicUpdateResponses = {
    /**
     * IP address updated successfully
     */
    200: string;
};

export type GetNicUpdateResponse = GetNicUpdateResponses[keyof GetNicUpdateResponses];

export type PostAuthLoginData = {
    body?: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Unauthorized: Invalid username or password
     */
    401: {
        success: false;
        message: 'Unauthorized: Invalid username or password';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        success: true;
        message: 'Login successful';
        data: {
            token: string;
            user_id: number;
            expires_at: number;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionErrors = {
    /**
     * Unauthorized: Invalid or missing session token
     */
    401: {
        success: false;
        message: 'Unauthorized: Invalid or missing session token';
    };
};

export type GetAuthSessionError = GetAuthSessionErrors[keyof GetAuthSessionErrors];

export type GetAuthSessionResponses = {
    /**
     * Session info retrieved successfully
     */
    200: {
        success: true;
        message: 'Session info retrieved successfully';
        data: {
            token: string;
            user_id: number;
            expires_at: number;
        };
    };
};

export type GetAuthSessionResponse = GetAuthSessionResponses[keyof GetAuthSessionResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Unauthorized: Invalid or missing session token
     */
    401: {
        success: false;
        message: 'Unauthorized: Invalid or missing session token';
    };
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logout successful
     */
    200: {
        success: true;
        message: 'Logout successful';
        data: null;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/domains';
};

export type GetDomainsResponses = {
    /**
     * Domains retrieved successfully
     */
    200: {
        success: true;
        message: 'Domains retrieved successfully';
        data: Array<{
            id: number;
            owner_id: number;
            subdomain: string;
            last_ipv4: string | null;
            last_ipv6: string | null;
            ddnsv2_api_secret: string;
        }>;
    };
};

export type GetDomainsResponse = GetDomainsResponses[keyof GetDomainsResponses];

export type PostDomainsData = {
    body?: {
        subdomain: string;
    };
    path?: never;
    query?: never;
    url: '/domains';
};

export type PostDomainsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Conflict: Domain with this subdomain already exists
     */
    409: {
        success: false;
        message: 'Conflict: Domain with this subdomain already exists';
    };
};

export type PostDomainsError = PostDomainsErrors[keyof PostDomainsErrors];

export type PostDomainsResponses = {
    /**
     * Domain created successfully
     */
    200: {
        success: true;
        message: 'Domain created successfully';
        data: {
            id: number;
        };
    };
};

export type PostDomainsResponse = PostDomainsResponses[keyof PostDomainsResponses];

export type DeleteDomainsDomainIdData = {
    body?: never;
    path: {
        domainID: string;
    };
    query?: never;
    url: '/domains/{domainID}';
};

export type DeleteDomainsDomainIdErrors = {
    /**
     * Domain with specified ID not found
     */
    404: {
        success: false;
        message: 'Domain with specified ID not found';
    };
};

export type DeleteDomainsDomainIdError = DeleteDomainsDomainIdErrors[keyof DeleteDomainsDomainIdErrors];

export type DeleteDomainsDomainIdResponses = {
    /**
     * Domain deleted successfully
     */
    200: {
        success: true;
        message: 'Domain deleted successfully';
        data: null;
    };
};

export type DeleteDomainsDomainIdResponse = DeleteDomainsDomainIdResponses[keyof DeleteDomainsDomainIdResponses];

export type GetDomainsDomainIdData = {
    body?: never;
    path: {
        domainID: string;
    };
    query?: never;
    url: '/domains/{domainID}';
};

export type GetDomainsDomainIdErrors = {
    /**
     * Domain with specified ID not found
     */
    404: {
        success: false;
        message: 'Domain with specified ID not found';
    };
};

export type GetDomainsDomainIdError = GetDomainsDomainIdErrors[keyof GetDomainsDomainIdErrors];

export type GetDomainsDomainIdResponses = {
    /**
     * Domain retrieved successfully
     */
    200: {
        success: true;
        message: 'Domain retrieved successfully';
        data: {
            id: number;
            owner_id: number;
            subdomain: string;
            last_ipv4: string | null;
            last_ipv6: string | null;
            ddnsv2_api_secret: string;
        };
    };
};

export type GetDomainsDomainIdResponse = GetDomainsDomainIdResponses[keyof GetDomainsDomainIdResponses];

export type PutDomainsDomainIdData = {
    body?: {
        subdomain: string;
        ddnsv2_api_secret?: string;
    };
    path: {
        domainID: string;
    };
    query?: never;
    url: '/domains/{domainID}';
};

export type PutDomainsDomainIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Domain with specified ID not found
     */
    404: {
        success: false;
        message: 'Domain with specified ID not found';
    };
};

export type PutDomainsDomainIdError = PutDomainsDomainIdErrors[keyof PutDomainsDomainIdErrors];

export type PutDomainsDomainIdResponses = {
    /**
     * Domain updated successfully
     */
    200: {
        success: true;
        message: 'Domain updated successfully';
        data: null;
    };
};

export type PutDomainsDomainIdResponse = PutDomainsDomainIdResponses[keyof PutDomainsDomainIdResponses];

export type GetDomainsDomainIdRecordsData = {
    body?: never;
    path: {
        domainID: string;
    };
    query?: never;
    url: '/domains/{domainID}/records';
};

export type GetDomainsDomainIdRecordsResponses = {
    /**
     * Records retrieved successfully
     */
    200: {
        success: true;
        message: 'Records retrieved successfully';
        data: Array<{
            id: number;
            domain_id: number;
            subdomain: string;
            type: 'A' | 'AAAA' | 'CNAME' | 'MX' | 'SRV' | 'TXT' | 'SPF' | 'CAA';
            record_data: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
        }>;
    };
};

export type GetDomainsDomainIdRecordsResponse = GetDomainsDomainIdRecordsResponses[keyof GetDomainsDomainIdRecordsResponses];

export type PostDomainsDomainIdRecordsData = {
    body?: {
        subdomain: string;
        type: 'A' | 'AAAA' | 'CNAME' | 'MX' | 'SRV' | 'TXT' | 'SPF' | 'CAA';
        record_data: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
    path: {
        domainID: string;
    };
    query?: never;
    url: '/domains/{domainID}/records';
};

export type PostDomainsDomainIdRecordsErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PostDomainsDomainIdRecordsError = PostDomainsDomainIdRecordsErrors[keyof PostDomainsDomainIdRecordsErrors];

export type PostDomainsDomainIdRecordsResponses = {
    /**
     * DNS record created successfully
     */
    200: {
        success: true;
        message: 'DNS record created successfully';
        data: {
            id: number;
        };
    };
};

export type PostDomainsDomainIdRecordsResponse = PostDomainsDomainIdRecordsResponses[keyof PostDomainsDomainIdRecordsResponses];

export type DeleteDomainsDomainIdRecordsRecordIdData = {
    body?: never;
    path: {
        domainID: string;
        recordID: string;
    };
    query?: never;
    url: '/domains/{domainID}/records/{recordID}';
};

export type DeleteDomainsDomainIdRecordsRecordIdErrors = {
    /**
     * Record with specified ID not found
     */
    404: {
        success: false;
        message: 'Record with specified ID not found';
    };
};

export type DeleteDomainsDomainIdRecordsRecordIdError = DeleteDomainsDomainIdRecordsRecordIdErrors[keyof DeleteDomainsDomainIdRecordsRecordIdErrors];

export type DeleteDomainsDomainIdRecordsRecordIdResponses = {
    /**
     * Record deleted successfully
     */
    200: {
        success: true;
        message: 'Record deleted successfully';
        data: null;
    };
};

export type DeleteDomainsDomainIdRecordsRecordIdResponse = DeleteDomainsDomainIdRecordsRecordIdResponses[keyof DeleteDomainsDomainIdRecordsRecordIdResponses];

export type GetDomainsDomainIdRecordsRecordIdData = {
    body?: never;
    path: {
        domainID: string;
        recordID: string;
    };
    query?: never;
    url: '/domains/{domainID}/records/{recordID}';
};

export type GetDomainsDomainIdRecordsRecordIdErrors = {
    /**
     * Record with specified ID not found
     */
    404: {
        success: false;
        message: 'Record with specified ID not found';
    };
};

export type GetDomainsDomainIdRecordsRecordIdError = GetDomainsDomainIdRecordsRecordIdErrors[keyof GetDomainsDomainIdRecordsRecordIdErrors];

export type GetDomainsDomainIdRecordsRecordIdResponses = {
    /**
     * Record retrieved successfully
     */
    200: {
        success: true;
        message: 'Record retrieved successfully';
        data: {
            id: number;
            domain_id: number;
            subdomain: string;
            type: 'A' | 'AAAA' | 'CNAME' | 'MX' | 'SRV' | 'TXT' | 'SPF' | 'CAA';
            record_data: string | number | boolean | null | {
                [key: string]: unknown;
            } | Array<unknown>;
        };
    };
};

export type GetDomainsDomainIdRecordsRecordIdResponse = GetDomainsDomainIdRecordsRecordIdResponses[keyof GetDomainsDomainIdRecordsRecordIdResponses];

export type PutDomainsDomainIdRecordsRecordIdData = {
    body?: {
        subdomain: string;
        type?: 'A' | 'AAAA' | 'CNAME' | 'MX' | 'SRV' | 'TXT' | 'SPF' | 'CAA';
        record_data?: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
    path: {
        domainID: string;
        recordID: string;
    };
    query?: never;
    url: '/domains/{domainID}/records/{recordID}';
};

export type PutDomainsDomainIdRecordsRecordIdErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Record with specified ID not found
     */
    404: {
        success: false;
        message: 'Record with specified ID not found';
    };
};

export type PutDomainsDomainIdRecordsRecordIdError = PutDomainsDomainIdRecordsRecordIdErrors[keyof PutDomainsDomainIdRecordsRecordIdErrors];

export type PutDomainsDomainIdRecordsRecordIdResponses = {
    /**
     * Record updated successfully
     */
    200: {
        success: true;
        message: 'Record updated successfully';
        data: null;
    };
};

export type PutDomainsDomainIdRecordsRecordIdResponse = PutDomainsDomainIdRecordsRecordIdResponses[keyof PutDomainsDomainIdRecordsRecordIdResponses];

export type DeleteAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type DeleteAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type DeleteAccountError = DeleteAccountErrors[keyof DeleteAccountErrors];

export type DeleteAccountResponses = {
    /**
     * Account deleted successfully
     */
    200: {
        success: true;
        message: 'Account deleted successfully';
        data: null;
    };
};

export type DeleteAccountResponse = DeleteAccountResponses[keyof DeleteAccountResponses];

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account';
};

export type GetAccountResponses = {
    /**
     * Account information retrieved successfully
     */
    200: {
        success: true;
        message: 'Account information retrieved successfully';
        data: {
            id: number;
            username: string;
            email: string;
        };
    };
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type PutAccountData = {
    body?: {
        username?: string;
        email?: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type PutAccountErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        message: 'Bad Request: Syntax or validation error in request';
    };
};

export type PutAccountError = PutAccountErrors[keyof PutAccountErrors];

export type PutAccountResponses = {
    /**
     * Account information updated successfully
     */
    200: {
        success: true;
        message: 'Account information updated successfully';
        data: null;
    };
};

export type PutAccountResponse = PutAccountResponses[keyof PutAccountResponses];

export type PutAccountPasswordData = {
    body?: {
        /**
         * Current password of the account
         */
        current_password: string;
        /**
         * New password for the account (at least 8 characters)
         */
        new_password: string;
    };
    path?: never;
    query?: never;
    url: '/account/password';
};

export type PutAccountPasswordErrors = {
    /**
     * Bad Request: Syntax or validation error in request
     */
    400: {
        success: false;
        message: 'Bad Request: Syntax or validation error in request';
    };
    /**
     * Current password is incorrect
     */
    401: {
        success: false;
        message: 'Current password is incorrect';
    };
};

export type PutAccountPasswordError = PutAccountPasswordErrors[keyof PutAccountPasswordErrors];

export type PutAccountPasswordResponses = {
    /**
     * Password changed successfully
     */
    200: {
        success: true;
        message: 'Password changed successfully';
        data: null;
    };
};

export type PutAccountPasswordResponse = PutAccountPasswordResponses[keyof PutAccountPasswordResponses];

export type PostAccountLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/logout';
};

export type PostAccountLogoutResponses = {
    /**
     * Logged out successfully
     */
    200: {
        success: true;
        message: 'Logged out successfully';
        data: null;
    };
};

export type PostAccountLogoutResponse = PostAccountLogoutResponses[keyof PostAccountLogoutResponses];
