// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:3003' | (string & {});
};

export type GetNicUpdateData = {
    body?: never;
    headers: {
        authorization: string;
    };
    path?: never;
    query: {
        hostname: string;
        myip: string | string;
    };
    url: '/nic/update';
};

export type GetNicUpdateErrors = {
    /**
     * Authentication information is missing or invalid
     */
    401: string;
};

export type GetNicUpdateError = GetNicUpdateErrors[keyof GetNicUpdateErrors];

export type GetNicUpdateResponses = {
    /**
     * IP address updated successfully
     */
    200: string;
};

export type GetNicUpdateResponse = GetNicUpdateResponses[keyof GetNicUpdateResponses];

export type PostAuthLoginData = {
    body?: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Invalid username or password
     */
    401: {
        success: false;
        message: string;
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful, returns session information
     */
    200: {
        success: true;
        data: {
            sessionToken: string;
        };
    };
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/domains';
};

export type GetDomainsErrors = {
    /**
     * Authentication information is missing or invalid
     */
    401: unknown;
};

export type GetDomainsResponses = {
    /**
     * A list of domains owned by the user
     */
    200: unknown;
};

export type PostDomainsData = {
    body?: {
        subdomain: string;
    };
    path?: never;
    query?: never;
    url: '/domains';
};

export type PostDomainsResponses = {
    200: unknown;
};

export type PutDomainsDomainIdData = {
    body?: {
        subdomain: string;
        ddnsv2_api_secret?: string;
    };
    path: {
        domainID: string;
    };
    query?: never;
    url: '/domains/{domainID}';
};

export type PutDomainsDomainIdResponses = {
    200: unknown;
};

export type GetDomainsDomainIdRecordsData = {
    body?: never;
    path: {
        domainID: string;
        id: string;
    };
    query?: never;
    url: '/domains/{domainID}/records';
};

export type GetDomainsDomainIdRecordsResponses = {
    200: unknown;
};

export type PostDomainsDomainIdRecordsData = {
    body?: {
        subdomain: string;
        type: 'A' | 'AAAA' | 'CNAME' | 'MX' | 'SRV' | 'TXT' | 'SPF' | 'CAA';
        record_data: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
    path: {
        domainID: string;
    };
    query?: never;
    url: '/domains/{domainID}/records';
};

export type PostDomainsDomainIdRecordsResponses = {
    200: unknown;
};

export type PutDomainsDomainIdRecordsRecordIdData = {
    body?: {
        subdomain: string;
        type?: 'A' | 'AAAA' | 'CNAME' | 'MX' | 'SRV' | 'TXT' | 'SPF' | 'CAA';
        record_data?: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown>;
    };
    path: {
        domainID: string;
        recordID: string;
    };
    query?: never;
    url: '/domains/{domainID}/records/{recordID}';
};

export type PutDomainsDomainIdRecordsRecordIdResponses = {
    200: unknown;
};
